# FEEDLY VARIABLES
FEEDLY_URL = "https://cloud.feedly.com/v3"
FEEDLY_ACCESS_TOKEN = "CHANGE_ME"

## WALLABAG VARIABLES
WALLABAG_URL = "https://CHANGE_ME"
WALLABAG_CLIENT_ID = "CHANGE_ME"
WALLABAG_CLIENT_SECRET = "CHANGE_ME"
WALLABAG_USERNAME = "CHANGE_ME"
WALLABAG_PASSWORD = "CHANGE_ME"
